expenseManager:
  environment:
    INFO_APP_VERSION: ${TAG_NAME}
    TZ: Australia/Melbourne
  image: cjmason8/expense-manager:${TAG_NAME}
  external_links:
    - postgres/postgres:postgres
    - authservice/authservice:authService
  volumes:
    - /applogs:/applogs
    - /docs:/docs
    - /resources:/resources
    - /etc/localtime:/etc/localtime

