expenseManager:
  extends:
    file: ../docker-compose.yml
    service: expenseManager
  environment:
    DB_URL: jdbc:postgresql://postgres:5432/expensemanager
    DB_USER: postgres
    DB_PASS: fjFSVC3Pm+d0Miy0ry3EWQ==
    DB_DRIVER: org.postgresql.Driver
    HIBERNATE_DIALECT: au.com.mason.expensemanager.dao.MyPostgreSQL94Dialect
    HIBERNATE_HBM2DDL_AUTO: update
    AUTH_SERVICE_END_POINT: http://authService:8080
    
