expenseManager:
  extends:
    file: ../docker-compose.yml
    service: expenseManager
  environment:
    DB_URL: jdbc:postgresql://172.17.0.1:5432/expensemanager
    DB_USER: postgres
    DB_PASS: d4xZEoqO7HS5i2jpJL8vGQ==
    DB_DRIVER: org.postgresql.Driver
    HIBERNATE_DIALECT: au.com.mason.expensemanager.dao.MyPostgreSQL94Dialect
    HIBERNATE_HBM2DDL_AUTO: update
    AUTH_SERVICE_END_POINT: http://172.17.0.1:8082
    
