expenseManager:
  extends:
    file: ../docker-compose.yml
    service: expenseManager
  environment:
    ENV: prd
    SPRING_PROFILES_ACTIVE: production
    DB_URL: jdbc:postgresql://postgres:5432/expensemanager
    DB_USER: postgres
    DB_PASS: CEZsmAWTbh0CnoagCJ/hRw==
    DB_DRIVER: org.postgresql.Driver
    HIBERNATE_DIALECT: au.com.mason.expensemanager.dao.MyPostgreSQL94Dialect
    HIBERNATE_HBM2DDL_AUTO: update
    AUTH_SERVICE_END_POINT: http://authService:8080
    REQUIRED_INFO: S4Eqz7962JO0qeRAfQdevwjQAfUilB86oZnyH0RD4zs= 
    ALPHA_VEC: E66YYu84iW50GE66
    RESOURCES_DIR: /resources
    REQ_ACCOUNT: icMZGRCb+RbYUKI5RX7HaM33C3mLyertwbUl2RhYdt8=  
    INFO_APP_VERSION: ${TAG_NAME}
    DOCS_LOCATION: /docs
    LOG_DIR: /applogs
